name: first

on:
  push:
    branches:
      - main


jobs:
  job-one:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: env | sort

  job-two:
    name: second job
    runs-on: windows-latest
    needs: job-one          # <- This makes job-two wait for job-one
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job-three:
    name: third job
    runs-on: ubuntu-latest
    needs: [job-one, job-two]   # <- This waits for both job-one & job-two
    steps:
      - name: step one
        run: echo "This is job three, running after job one & two"
       - name: AWS Sustainability Scanner GitHub Action
         # You may pin to the exact commit or the version.
         # uses: aws-actions/sustainability-scanner@d6067411fc5290a836e3ebcf388c746d83cf0e9f
       uses: aws-actions/sustainability-scanner@v1
  
          

        
