name: first

on: [push]

jobs:
  job-one:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "This is step one of job one"

      - name: step two
        run: echo "This is step two of job one"

  job-two:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        run: echo "This is step one of job two"

      - name: step two
        run: echo "This is step two of job two"
