name: first

on: [push]

jobs:
  job-one:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v3

      - name: step two
        run: env | sort

  job-two:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v3

      - name: step two
        run: "Get-ChildItem Env: | Sort-Object Name"
